# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('mail', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mail')),
                ('nacimiento', models.DateField(default=datetime.date.today, verbose_name='Nacimiento')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('color_pelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Color de pelo')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=30, verbose_name='Documento')),
                ('mail', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mail')),
                ('experiencia', models.TextField(blank=True, null=True, verbose_name='Experiencia')),
                ('nacimiento', models.DateField(default=datetime.date.today, verbose_name='Nacimiento')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peluqueria.Especialidad'),
        ),
    ]
