# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 00:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0, verbose_name='Cantidad')),
                ('descuento', models.FloatField(default=0, verbose_name='Descuento')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.Empleado')),
            ],
            options={
                'ordering': ('factura',),
                'verbose_name_plural': 'Detalle Facturas',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha')),
                ('total', models.FloatField(default=0, verbose_name='Precio')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.Cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.Estado')),
            ],
            options={
                'ordering': ('numero',),
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Metodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('precio', models.FloatField(default=0, verbose_name='Precio')),
            ],
            options={
                'ordering': ('producto',),
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Nacimiento')),
                ('inicial', models.FloatField(default=0, verbose_name='Inicial')),
                ('actual', models.FloatField(default=0, verbose_name='Actual')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.Producto')),
            ],
            options={
                'ordering': ('producto',),
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Tipos de Productos',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.TipoProducto'),
        ),
        migrations.AddField(
            model_name='factura',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.MetodoPago'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.Factura'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.Producto'),
        ),
    ]
