# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0003_auto_20160926_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='descuento',
            field=models.FloatField(default=0, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='factura',
            name='subtotal',
            field=models.FloatField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.CharField(max_length=100, verbose_name='Numero'),
        ),
    ]
