# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0004_auto_20161008_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='precio',
            field=models.FloatField(default=0, verbose_name='Precio'),
        ),
    ]
