# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0006_auto_20161009_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_reporte',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fecha Reporte'),
        ),
    ]
