# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0007_factura_fecha_reporte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariosempleados',
            options={'ordering': ('fecha',), 'verbose_name_plural': 'Horarios Empleados'},
        ),
        migrations.RemoveField(
            model_name='horariosempleados',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='horariosempleados',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='horariosempleados',
            name='fecha',
            field=models.CharField(default='20160101', max_length=8, verbose_name='Fecha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horariosempleados',
            name='turno',
            field=models.CharField(choices=[('MA', 'Manana'), ('TA', 'Tarde'), ('NO', 'Noche'), ('FA', 'Franco')], default='MA', max_length=2),
        ),
    ]
